### ISSUE TITLE
you're leaking your coverage reporter's token

### ISSUE THREAD

**Issue by sundowndev** [toshimaru/nyan#97]
https://github.com/toshimaru/nyan/blob/master/.github/workflows/coverage.yml#L14

**Comment by toshimaru** [comment]
This is intentional. Thanks 👍 

> Should I keep my Test Reporter ID secret?
> Your repo's test coverage ID is only used to identify your repo when submitting test coverage payloads. It can't be used to access any of your data.

[Finding Your Test Coverage ID](https://docs.codeclimate.com/docs/finding-your-test-coverage-token#should-i-keep-my-test-reporter-id-secret)
